name: hippoit
favicon: null
layout_spectrum: 0.39763
typography_spectrum: 0.28202
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#3b6b93'
    - '#4a4647'
    - '#e1e1e1'
    - '#8b8a8b'
  brandStrength: 0.5
  lightness: 0.16857459186576307
  saturation: 0.22723803180269897
  rhythmicContrast: 0.45538495434448123
purpose: []
